In [4]:
# !pip install pandas

In [3]:
import pandas as pd

In [3]:
pd.__version__

'3.0.5'

In [1]:
# creating data frame
data= {
    "name": ["bob", "aman", "charles", "segmecth"],
    "age":[24,25,27,26]
    }

In [4]:
df= pd.DataFrame(data)

In [5]:
df

       name  age
0       bob   24
1      aman   25
2   charles   27
3  segmecth   26

In [8]:
titanic_df= pd.read_csv("titanic_train.csv", delimiter=",")

In [9]:
titanic_df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S