In [9]:
import pandas as pd

titanic_df= pd.read_csv("clean_titanic_train.csv")

In [ ]:
data= data.astype({"Age":"int32"})
data.Age=abs(data.Age)
data

,Unnamed: 0,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Initials
0,0,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,0,S,Mr
1,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,1,C,Mrs
2,2,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,0,S,Miss
3,3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,1,S,Mrs
4,4,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,0,S,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,884,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,0,S,Rev
885,885,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,1,S,Miss
886,886,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21,1,2,W./C. 6607,23.4500,0,S,Miss
887,887,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,1,C,Mr
888,888,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,0,Q,Mr

In [8]:
data[data.Sex.isin(["M","F"])]

Empty DataFrame
Columns: [Unnamed: 0, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, Initials]
Index: []