In [1]:
import pandas as pd
# !pip install scikit-learn
import sklearn

titanic_df= pd.read_csv("clean_titanic_train.csv")

### One-Hot encoding
for nominal(data doesnt have priority over other : eg gender) data encoding

In [2]:
titanic_df.Sex

0        male
1      female
2      female
3      female
4        male
        ...
884      male
885    female
886    female
887      male
888      male
Name: Sex, Length: 889, dtype: str

In [3]:
pd.get_dummies(titanic_df, columns=["Sex"], dtype=int).head(5)

,Unnamed: 0,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Initials,Sex_female,Sex_male
0,0,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,0,S,Mr,0,1
1,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,1,C,Mrs,1,0
2,2,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,0,S,Miss,1,0
3,3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,1,S,Mrs,1,0
4,4,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,0,S,Mr,0,1

### Problem with one hot encoding

it creates sparce matrix. i.e a lot of 0,1 columns. this causes slow processing speed and consumes more space

In [4]:
from sklearn.preprocessing import OneHotEncoder

one_hot_encoder= OneHotEncoder(sparse_output=False)

In [6]:
one_hot_encoder.fit_transform(
    titanic_df[["Sex", "Embarked"]]
)

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]], shape=(889, 5))

In [8]:
one_hot_encoder.categories_

[array(['female', 'male'], dtype=object), array(['C', 'Q', 'S'], dtype=object)]

In [21]:
# one_hot_encoder.inverse_transform(
#    [ [1],[0]]
# )

### Ordinal Data (Data with natural order)

In [9]:
titanic_df.Embarked

0      S
1      C
2      S
3      S
4      S
      ..
884    S
885    S
886    S
887    C
888    Q
Name: Embarked, Length: 889, dtype: str

In [10]:
titanic_df["encoded_embarked"] , rule= pd.factorize(titanic_df.Embarked)
titanic_df.head()

,Unnamed: 0,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Initials,encoded_embarked
0,0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0,S,Mr,0
1,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,1,C,Mrs,1
2,2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0,S,Miss,0
3,3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,1,S,Mrs,0
4,4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0,S,Mr,0

In [11]:
titanic_df.encoded_embarked.value_counts()

encoded_embarked
0    644
1    168
2     77
Name: count, dtype: int64

In [12]:
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder

In [13]:
ordinal_encoder= OrdinalEncoder()

In [15]:
encoded_result=ordinal_encoder.fit_transform(titanic_df[["Embarked"]])

In [17]:
ordinal_encoder.categories_

[array(['C', 'Q', 'S'], dtype=object)]

In [19]:
ordinal_encoder.inverse_transform(
    [
        [1],[2],[0], [1]
    ]
)

array([['Q'],
       ['S'],
       ['C'],
       ['Q']], dtype=object)

In [22]:
final_df= titanic_df.drop(
    ["Name", "Ticket", "Initials", "encoded_embarked"], axis=1
)

In [23]:
final_df

,Unnamed: 0,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,0,0,3,male,22.0,1,0,7.2500,0,S
1,1,1,1,female,38.0,1,0,71.2833,1,C
2,2,1,3,female,26.0,0,0,7.9250,0,S
3,3,1,1,female,35.0,1,0,53.1000,1,S
4,4,0,3,male,35.0,0,0,8.0500,0,S
...,...,...,...,...,...,...,...,...,...,...
884,884,0,2,male,27.0,0,0,13.0000,0,S
885,885,1,1,female,19.0,0,0,30.0000,1,S
886,886,0,3,female,21.0,1,2,23.4500,0,S
887,887,1,1,male,26.0,0,0,30.0000,1,C
888,888,0,3,male,32.0,0,0,7.7500,0,Q

In [24]:
one_hot_encoder= OneHotEncoder(sparse_output=False)
ordinal_encoder= OrdinalEncoder(dtype=int)

In [28]:
age_embarked_encoded= one_hot_encoder.fit_transform(titanic_df[["Sex", "Embarked"]])
pclass_encoded= ordinal_encoder.fit_transform(titanic_df[["Pclass"]])

In [29]:
final_df.Pclass= pclass_encoded

In [31]:
pd.get_dummies(final_df, columns=["Sex", "Embarked"], dtype=int)

,Unnamed: 0,Survived,Pclass,Age,SibSp,Parch,Fare,Cabin,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,0,0,2,22.0,1,0,7.2500,0,0,1,0,0,1
1,1,1,0,38.0,1,0,71.2833,1,1,0,1,0,0
2,2,1,2,26.0,0,0,7.9250,0,1,0,0,0,1
3,3,1,0,35.0,1,0,53.1000,1,1,0,0,0,1
4,4,0,2,35.0,0,0,8.0500,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,884,0,1,27.0,0,0,13.0000,0,0,1,0,0,1
885,885,1,0,19.0,0,0,30.0000,1,1,0,0,0,1
886,886,0,2,21.0,1,2,23.4500,0,1,0,0,0,1
887,887,1,0,26.0,0,0,30.0000,1,0,1,1,0,0
888,888,0,2,32.0,0,0,7.7500,0,0,1,0,1,0