In [1]:
import pandas as pd

titanic_df= pd.read_csv("clean_titanic_train.csv")

titanic_df.head(5)

,Unnamed: 0,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Initials
0,0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0,S,Mr
1,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,1,C,Mrs
2,2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0,S,Miss
3,3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,1,S,Mrs
4,4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0,S,Mr

### Correlation
we can remove strong correlated columns

In [4]:
# titanic_df.drop("Unnamed: 0", axis=1, inplace=True)
titanic_df.corr(numeric_only=True)

          Survived    Pclass       Age     SibSp     Parch      Fare     Cabin
Survived  1.000000 -0.335549 -0.083703 -0.034040  0.083151  0.255290  0.313435
Pclass   -0.335549  1.000000 -0.350772  0.081656  0.016824 -0.548193 -0.723815
Age      -0.083703 -0.350772  1.000000 -0.264975 -0.187195  0.095024  0.239112
SibSp    -0.034040  0.081656 -0.264975  1.000000  0.414542  0.160887 -0.038657
Parch     0.083151  0.016824 -0.187195  0.414542  1.000000  0.217532  0.039101
Fare      0.255290 -0.548193  0.095024  0.160887  0.217532  1.000000  0.480425
Cabin     0.313435 -0.723815  0.239112 -0.038657  0.039101  0.480425  1.000000

In [5]:
import scipy.stats as stats

In [7]:
contengency_table= pd.crosstab(titanic_df.Pclass, titanic_df.Survived)
contengency_table

Survived    0    1
Pclass
1          80  134
2          97   87
3         372  119

In [8]:
chi2_score, pvalue, dof, expected_frequency= stats.chi2_contingency(contengency_table)

In [13]:
print(f"Chi-Squared test score= {round(chi2_score, 3)}")
print(f"p-value= {round(pvalue, 5)}")

Chi-Squared test score= 100.98
p-value= 0.0

In [15]:
contingency_table= pd.crosstab(titanic_df.Cabin, titanic_df.Parch)

In [18]:
chi2_score, pvalue, dof,_= stats.chi2_contingency(contingency_table)

In [17]:
print(f"Chi-Squared test score= {round(chi2_score, 3)}")
print(f"p-value= {round(pvalue, 5)}")

Chi-Squared test score= 13.867
p-value= 0.03116