In [1]:
import numpy as np
import pandas as pd

In [2]:
titanic_df= pd.read_csv("titanic_train.csv")
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
pd.crosstab(
    index= titanic_df.Sex,
    columns=titanic_df.Survived,
    margins=True,
    margins_name="Total",
    colnames=["Rate of survival"],
    rownames=["Gender"],
    # aggfunc= "mean",
    # values=titanic_df.Fare
)

Rate of survival    0    1  Total
Gender
female             81  233    314
male              468  109    577
Total             549  342    891

In [10]:
pd.crosstab(
    titanic_df.Sex,
    [titanic_df.Survived, titanic_df.Pclass],
    margins =True
)

Survived   0             1           All
Pclass     1   2    3    1   2    3
Sex
female     3   6   72   91  70   72  314
male      77  91  300   45  17   47  577
All       80  97  372  136  87  119  891

In [11]:
titanic_df.Embarked.unique() #get unique values

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [12]:
titanic_df.Embarked.nunique(dropna= False)

4

In [ ]:
# sum(), prod(), cumsum(), var(), std(), mean(), quantile()
titanic_df.Age.sum()
# titanic_df.Name.sum() #this one concatinates all the strings

np.float64(21205.17)

In [14]:
titanic_df.Age.quantile(q=0.25)

np.float64(20.125)

In [15]:
titanic_df.Fare.var()

np.float64(2469.436845743116)

In [16]:
titanic_df.Embarked.mode()

0    S
Name: Embarked, dtype: str

In [17]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [18]:
titanic_df["Age"].add(titanic_df["Fare"])

0       29.2500
1      109.2833
2       33.9250
3       88.1000
4       43.0500
         ...
886     40.0000
887     49.0000
888         NaN
889     56.0000
890     39.7500
Length: 891, dtype: float64

In [ ]:
titanic_df.isna().sum(axis=0) #1-> horizontal, 0->Vertical

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [20]:
#group by
sample_df=titanic_df[["Sex", "Fare", "Age", "Survived", "Embarked"]]
group_by_gender= sample_df.groupby(by="Sex")
group_by_gender

In [21]:
group_by_gender.mean(numeric_only=True)

             Fare        Age  Survived
Sex
female  44.479818  27.915709  0.742038
male    25.523893  30.726645  0.188908

In [22]:
group_by_gender.value_counts(["Survived"])

Sex     Survived
female  1           233
        0            81
male    0           468
        1           109
Name: count, dtype: int64

In [23]:
group_by_two= titanic_df.groupby(by= ["Embarked", "Survived"]) #TRY TO USE GROUP BY ON COLUMN WITH FEW UNIQUE VALUES. EXAMPLE TO NOT USE: AGE WHICH MAY HAVE 100 UNIQUE VALUES

In [24]:
group_by_two.count()

                   PassengerId  Pclass  Name  Sex  Age  SibSp  Parch  Ticket  \
Embarked Survived
C        0                  75      75    75   75   51     75     75      75
         1                  93      93    93   93   79     93     93      93
Q        0                  47      47    47   47   20     47     47      47
         1                  30      30    30   30    8     30     30      30
S        0                 427     427   427  427  353    427    427     427
         1                 217     217   217  217  201    217    217     217

                   Fare  Cabin
Embarked Survived
C        0           75     17
         1           93     52
Q        0           47      2
         1           30      2
S        0          427     49
         1          217     80

In [25]:
#Correlation and Covariance

titanic_df[["Age", "Fare"]].cov()

             Age         Fare
Age   211.019125    73.849030
Fare   73.849030  2469.436846

In [26]:
titanic_df[["Age", "Fare"]].corr()

           Age      Fare
Age   1.000000  0.096067
Fare  0.096067  1.000000

In [27]:
#sample
sample_df = titanic_df.sample(n=300, random_state=999)

In [28]:
sample_df.mean(numeric_only=True)

PassengerId    451.633333
Survived         0.366667
Pclass           2.353333
Age             29.880250
SibSp            0.530000
Parch            0.380000
Fare            31.413222
dtype: float64

In [29]:
sample_df[["Age", "Fare"]].corr()

          Age     Fare
Age   1.00000  0.03441
Fare  0.03441  1.00000